name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      continue-on-error: true
      run: |
        flake8
    - name: Docstring Tests
      continue-on-error: true
      run: |
        pydocstyle
    - name: Code Style
      continue-on-error: true
      run: |
        pycodestyle
    - name: Pylint
      continue-on-error: true
      run: |
        pylint
    - name: Security Analysis
      continue-on-error: true
      run: |
        bandit --ini setup.cfg
    - name: MyPy Type Analysis
      continue-on-error: true
      run: |
        mypy
    - name: PyTest unit tests
      continue-on-error: true
      run: |
        pytest tests -s -v --cov=./CalibrationCode --cov=./tests --cov-report=term --cov-branch
